replicaCount: 2

image:
  repository: 546338373444.dkr.ecr.us-east-1.amazonaws.com/llm-inference
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: 2000m
    memory: 6Gi
  requests:
    cpu: 1000m
    memory: 4Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

serviceAccount:
  create: true
  name: ""
